[package]
name = "nofs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nofs"
path = "src/main.rs"

[dependencies]
fuser = "0.15"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
libc = "0.2"
eframe = "0.31"
polars = { version = "0.46", features = ["avro"] }
sha2 = "0.10"
hex = "0.4"
fastcdc = "3.2.1"
reed-solomon-erasure = "6"
crc32fast = "1"
